### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Bukunmikuti** [Bukunmikuti/wed#1]
- [ ] fix Map
- [ ] Change pictures/slide movement
- [ ] Disable scroll in loading screen
- [ ] Make first venue card hover-active
